### ISSUE TITLE
develop分支在2.7的情况，简化URL解析有问题。

### ISSUE THREAD

**Issue by linzhiqiang0514** [apache/incubator-dubbo-admin#313]
/**
     * Convert provider list to ServiceDTO list
     *
     * @param providers list of providers
     * @return ServiceDTO list of front page
     */
    public Set<ServiceDTO> convertProviders2DTO(List<Provider> providers) {
        Set<ServiceDTO> result = new TreeSet<>();
        for (Provider provider : providers) {
            Map<String, String> map = StringUtils.parseQueryString(provider.getParameters());
            String app = provider.getApplication();
            String service = map.get(Constants.INTERFACE_KEY);
            String group = map.get(Constants.GROUP_KEY);
            String version = map.get(Constants.VERSION_KEY);
            ServiceDTO s = new ServiceDTO();
            s.setAppName(app);
            s.setService(service);
            s.setGroup(group);
            s.setVersion(version);
            result.add(s);
        }
        return result;
    }

请求：http://localhost:8080/api/dev/service?pattern=service&filter=test%2Fcom.ffcs.crmd.test.facade.UserFacade:1.0.0

返回：
[{"service":null,"appName":"testDaoApp","group":"test","version":"1.0.0"}]

应该是URL简化后，解析不完整。

**Comment by nzomkxia** [comment]
是在简化URL注册的时候出现的么？我复现一下

**Comment by linzhiqiang0514** [comment]
对，dubbo2.7的配置，我贴出来，你稍等。
```
dubbo:
  application:
#    name: ${spring.applicaiton.name}
    qos-enable: false
  registry:
#    address: zookeeper://localhost:2181
    file: ${user.home}/dubbo-cache/${dubbo.applicaiton.name}/dubbo.cache
#    username: admin
#    password: 123456
    group: dubbo
    simplified: true
#  metadata-report:
#    address: zookeeper://localhost:2181
  config-center:
#    address: zookeeper://localhost:2181
    configFile: dubbo.properties
  protocol:
    port: -1
    threads: 500
  provider:
    timeout: 5000
    cluster: failfast
    retries: 0
    delay: -1
  consumer:
    init: true
    check: false
  monitor:
    protocol: registry
```

配置了这个。
    simplified: true
